### ISSUE TITLE
Webpack unable to compile due to type discrepancies between ajv and ajv-formats

### ISSUE THREAD

**Issue by svile** [ajv-validator/ajv-formats#19] opened 2021-03-18 08:11 UTC
Hello, I'm trying to compile a typescript project using Webpack 5, but I'm running in the following error:
```
TS2345: Argument of type 'import(".../node_modules/ajv/dist/ajv").default' is not assignable to parameter of type 'import(".../node_modules/ajv-formats/node_modules/ajv/dist/core").default'.
  Types of property 'opts' are incompatible.
    Type 'import(".../node_modules/ajv/dist/core").InstanceOptions' is not assignable to type 'import(".../node_modules/ajv-formats/node_modules/ajv/dist/core").InstanceOptions'.
      Type 'InstanceOptions' is not assignable to type 'CurrentOptions'.
        Types of property 'keywords' are incompatible.
```

I'm using ajv v7.2.1 and ajv-formats v1.5.1 with the default code example:
```
import Ajv from "ajv"
import addFormats from "ajv-formats"

const ajv = new Ajv()
addFormats(ajv)
```

If I remove the line `addFormats(ajv)` it compiles fine.

Here is my `tsconfig.js`
```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "jsx": "react",
    "lib": [
      "dom",
      "ES2019"
    ],
    "module": "commonjs",
    "target": "ES2019",
    "allowJs": true,
    "sourceMap": true,
    "moduleResolution": "node",
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "experimentalDecorators": true,
    "noEmitOnError": true,
    "removeComments": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "importHelpers": true,
    "noEmitHelpers": true,
    "forceConsistentCasingInFileNames": true,
    "esModuleInterop": true,
    "strict": true
  }
}
```

Any help would be much appreciated

**Comment by epoberezkin** [comment] 2021-03-27 08:18
duplicate of #13

**Closed by epoberezkin** 2021-03-27 08:18 UTC

**Comment by cyberwombat** [comment] 2021-04-27 16:09
This is still an issue and #13 does nothing to solve this. I have ajv 8.0.0 and ajv-formats 2.0.2 and getting that same error

**Comment by cyberwombat** [comment] 2021-04-27 16:30
Ok. 8.0.0 listed in peer deps was incompatible as well as 8.1.0. 8.2.0 works though.
