### ISSUE TITLE
How can i use ajv-formats in JS ?

### ISSUE THREAD

**Issue by sabrineChe** [ajv-validator/ajv-formats#27] opened 2021-04-27 07:25 UTC
I'm using the minified version of [ajv7](https://cdnjs.cloudflare.com/ajax/libs/ajv/7.2.2/ajv7.min.js) in Javascript, and i want to support other formats, which are in the ajv-formats package.
I want to import ajv-formats, which is written in typescript, to my Javascript project. 
Is there a possibility to make it ?
Does a minified version of ajv-formats exist ?

**Comment by epoberezkin** [comment] 2021-11-07 16:35
I should be usable with require - please submit an example that doesn't work - possibly duplicate of #28?

closing this one - please resubmit with more details if needed.

**Closed by epoberezkin** 2021-11-07 16:35 UTC
